### ISSUE TITLE
Add `quit(save = "no")` to the script templates

### ISSUE THREAD

**Issue by Moohan** [Public-Health-Scotland/phstemplates#49]
Per the latest guidance from the data science team with the PWB should we add `quit(save = "no")`?

**Comment by alan-y** [comment]
I think it's a good suggestion but should we leave it commented so that the user can uncomment if needed? I think this is needed mainly for scheduling or if you are waiting for something longer to finish running. I'm just trying to think about if somebody hits 'run all' and then comes back to unexpectely find R has shut down!
